all:
	gcc -Wall -Wextra buzzer.c -pthread -lwiringPi -o buzzer.exe
	gcc -Wall -Wextra -DTEST blinkt.c -pthread -lwiringPi -o blinkt.exe
	gcc -Wall -Wextra -DRAINTEST blinkt.c -pthread -lwiringPi -o rainbow.exe
	gcc -Wall -Wextra -DTEST alphanum.c -pthread -lwiringPi -o alphanum.exe



