all:
	gcc -Wall -Wextra buzzer.c -pthread -lwiringPi -o buzzer.exe
	gcc -Wall -Wextra -DBTEST blinkt.c -pthread -lwiringPi -o blinkt.exe
	gcc -Wall -Wextra -DTEST blinkt.c -pthread -lwiringPi -o rainbow.exe
	gcc -Wall -Wextra -DTEST alphanum.c -pthread -lwiringPi -o alphanum.exe
	gcc -Wall -Wextra weather.c -pthread -lwiringPi -o weather.exe




